version: '3.8'

services:
  postgres:
    image: postgres:15  # PostgreSQL 15+ for advanced JSONB features
    environment:
      POSTGRES_DB: guideline_ingestion
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine  # Redis 7.2+ for Celery broker/backend
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .  # Uses Python 3.12-slim base image
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=guideline_ingestion
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=django-insecure-docker-development-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"

  celery:
    build: .  # Uses Python 3.12-slim base image
    environment:
      - POSTGRES_DB=guideline_ingestion
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - DJANGO_DEBUG=True
      - DJANGO_SECRET_KEY=django-insecure-docker-development-key-change-in-production
      - OPENAI_API_KEY=${OPENAI_API_KEY:-your_openai_api_key_here}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - .:/app
    command: celery -A config worker --loglevel=info

volumes:
  postgres_data: